import AppKit

/// nspasteboard.org が定める非公式規約のUTI。パスワードマネージャ等がコピー時に付与する。
private enum PasteboardConcealment {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

/// `NSPasteboard.changeCount` のポーリングによりクリップボードの変化を検出し、
/// スキップ条件（機密・一時・空・過大）を判定したうえで `HistoryStore` へ挿入する。
///
/// macOS にはクリップボード変更通知APIが存在しないため、ポーリングで実装する（設計書 5節）。
/// `changeCount` の取得自体は極めて軽量なため、間隔を短く（既定0.3秒）しても常時負荷は小さい。
/// 実データの読み出し・DB書き込みは変化を検出した時のみ行う。
public final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let settings: Settings
    private let historyStore: HistoryStore

    private var lastChangeCount: Int
    private var timer: Timer?

    /// 新規挿入が成功するたびに呼ばれる。`SearchIndex.append` に接続することで、
    /// DBを再読み込みせずにインメモリ検索インデックスへ追記できるようにする（設計書6.1）。
    public var onInsert: ((IndexEntry) -> Void)?

    public init(settings: Settings, historyStore: HistoryStore) {
        self.settings = settings
        self.historyStore = historyStore
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    public func start() {
        let interval = settings.pollingInterval
        let newTimer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // tolerance を設けることで OS のタイマーコアレッシングを許可し、省電力化する（設計書5節）
        newTimer.tolerance = 0.1
        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        handleChange()
    }

    private func handleChange() {
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)

        // 一時データ・自動生成データは常にスキップ
        if typeStrings.contains(PasteboardConcealment.transient)
            || typeStrings.contains(PasteboardConcealment.autoGenerated) {
            return
        }

        // 機密データはスキップ（設定で無効化可能）
        if settings.skipConcealed && typeStrings.contains(PasteboardConcealment.concealed) {
            return
        }

        // テキスト優先: リッチテキストのコピーはテキストと画像表現を同時に持つことがあり、
        // その場合はテキストとして扱いたいため、使えるテキストがあれば画像判定より先に処理する。
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let data = Data(text.utf8)

            // 過大なテキストはスキップ（設定可能、既定5MB）
            if data.count > settings.maxTextBytes { return }

            let hash = sha256Hex(data)
            if isSameAsLatest(hash: hash) { return }
            let searchKey = Normalizer.normalize(text)
            let previewText = String(text.prefix(200))

            // コピー元アプリは検出時点の frontmostApplication（近似値。設計書 5.2）
            let frontApp = NSWorkspace.shared.frontmostApplication

            let newItem = HistoryStore.NewItem(
                createdAt: Int64(Date().timeIntervalSince1970 * 1000),
                kind: .text,
                previewText: previewText,
                searchKey: searchKey,
                contentHash: hash,
                sourceAppBundleID: frontApp?.bundleIdentifier,
                sourceAppName: frontApp?.localizedName,
                representations: [
                    HistoryStore.NewRepresentation(uti: PasteboardTextType.utf8PlainText, data: data)
                ]
            )

            insert(newItem, searchKey: searchKey)
            return
        }

        // テキストが使えない場合に限り、画像として取り込む
        guard let (uti, data) = PasteboardImageType.orderedUTIs.lazy.compactMap({ uti -> (String, Data)? in
            guard let data = self.pasteboard.data(forType: NSPasteboard.PasteboardType(uti)), !data.isEmpty else { return nil }
            return (uti, data)
        }).first else { return }

        // 過大な画像はスキップ（設定可能、既定20MB）
        if data.count > settings.maxImageBytes { return }

        let hash = sha256Hex(data)
        if isSameAsLatest(hash: hash) { return }
        let previewText = imagePreviewText(uti: uti, data: data)
        let searchKey = Normalizer.normalize(previewText)

        // コピー元アプリは検出時点の frontmostApplication（近似値。設計書 5.2）
        let frontApp = NSWorkspace.shared.frontmostApplication

        let newItem = HistoryStore.NewItem(
            createdAt: Int64(Date().timeIntervalSince1970 * 1000),
            kind: .image,
            previewText: previewText,
            searchKey: searchKey,
            contentHash: hash,
            sourceAppBundleID: frontApp?.bundleIdentifier,
            sourceAppName: frontApp?.localizedName,
            representations: [
                HistoryStore.NewRepresentation(uti: uti, data: data)
            ]
        )

        insert(newItem, searchKey: searchKey)
    }

    /// 直前（最新）のレコードと同一内容かどうかを判定する。
    /// 連続する同一内容のみを対象とし、過去データとの重複は許容する（設計書 4.4）。
    /// メモリ上に前回ハッシュをキャッシュせず、毎回 `HistoryStore` に問い合わせる。
    /// 再起動後や「履歴を全消去」後に古い状態が残って登録が誤って抑制されるのを避けるためであり、
    /// コピー操作1回あたり `idx_items_created_at` を使う1クエリだけなのでコストは無視できる。
    private func isSameAsLatest(hash: String) -> Bool {
        do {
            return try historyStore.latestContentHash() == hash
        } catch {
            // DB読み出しに失敗しても登録自体は止めない（同一ではないとみなす）
            NSLog("ClipHistory: failed to read latest content hash: \(error)")
            return false
        }
    }

    /// 一覧行に表示する説明テキストを組み立てる。フォーマット名と、取得できればピクセルサイズを付す。
    private func imagePreviewText(uti: String, data: Data) -> String {
        let formatName: String
        switch uti {
        case "public.png": formatName = "PNG"
        case "public.jpeg": formatName = "JPEG"
        case "public.tiff": formatName = "TIFF"
        default: formatName = uti
        }

        // Retina スクリーンショットでは NSImage.size（pt）が実寸と食い違うため、
        // NSBitmapImageRep のピクセルサイズを優先して使う。
        if let bitmap = NSBitmapImageRep(data: data) {
            return "[Image] \(formatName) \(bitmap.pixelsWide)×\(bitmap.pixelsHigh)"
        }
        if let image = NSImage(data: data) {
            return "[Image] \(formatName) \(Int(image.size.width))×\(Int(image.size.height))"
        }
        return "[Image] \(formatName)"
    }

    /// `HistoryStore` への挿入と `onInsert` 通知、エラー時のログ出力をテキスト・画像で共通化する。
    private func insert(_ item: HistoryStore.NewItem, searchKey: String) {
        do {
            let itemID = try historyStore.insert(item)
            onInsert?(IndexEntry(id: itemID, createdAt: item.createdAt, searchKey: searchKey))
        } catch {
            // DB書き込みに失敗しても監視ループ自体は継続する
            NSLog("ClipHistory: failed to insert history item: \(error)")
        }
    }
}
