import AppKit

/// nspasteboard.org が定める非公式規約のUTI。パスワードマネージャ等がコピー時に付与する。
private enum PasteboardConcealment {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

/// `NSPasteboard.changeCount` のポーリングによりクリップボードの変化を検出し、
/// スキップ条件（機密・一時・空・過大）を判定したうえで `HistoryStore` へ挿入する。
///
/// macOS にはクリップボード変更通知APIが存在しないため、ポーリングで実装する（設計書 5節）。
/// `changeCount` の取得自体は極めて軽量なため、間隔を短く（既定0.3秒）しても常時負荷は小さい。
/// 実データの読み出し・DB書き込みは変化を検出した時のみ行う。
public final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let settings: Settings
    private let historyStore: HistoryStore

    private var lastChangeCount: Int
    private var timer: Timer?

    /// 新規挿入が成功するたびに呼ばれる。`SearchIndex.append` に接続することで、
    /// DBを再読み込みせずにインメモリ検索インデックスへ追記できるようにする（設計書6.1）。
    public var onInsert: ((IndexEntry) -> Void)?

    /// 自アプリがクリップボードへ書き込んだ直後の changeCount。
    /// 次回ポーリングでこの値と一致した場合のみ、その1回に限り検出をスキップする
    /// （設計書 5.1「自アプリ由来の即時再検出」）。
    /// 注意: フェーズ2以降のパネル選択確定時の書き戻しは、この仕組みでは抑制しない
    /// （選択によるクリップボード書き込みは、新規レコードとして履歴に残るのが仕様のため）。
    private var suppressedChangeCount: Int?

    public init(settings: Settings, historyStore: HistoryStore) {
        self.settings = settings
        self.historyStore = historyStore
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    public func start() {
        let interval = settings.pollingInterval
        let newTimer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // tolerance を設けることで OS のタイマーコアレッシングを許可し、省電力化する（設計書5節）
        newTimer.tolerance = 0.1
        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// このフェーズでは呼び出し元は存在しないが、フェーズ2以降で自アプリがクリップボードへ
    /// 書き込む処理（パネルからの通常の書き戻しを除く用途）を実装する際に使う想定のAPI。
    public func markOwnWrite() {
        suppressedChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if let suppressed = suppressedChangeCount, suppressed == current {
            suppressedChangeCount = nil
            return
        }

        handleChange()
    }

    private func handleChange() {
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)

        // 一時データ・自動生成データは常にスキップ
        if typeStrings.contains(PasteboardConcealment.transient)
            || typeStrings.contains(PasteboardConcealment.autoGenerated) {
            return
        }

        // 機密データはスキップ（設定で無効化可能）
        if settings.skipConcealed && typeStrings.contains(PasteboardConcealment.concealed) {
            return
        }

        // v1のこのフェーズで扱う型は public.utf8-plain-text のみ
        guard let text = pasteboard.string(forType: .string) else { return }

        // 空、または空白文字のみはスキップ
        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return }

        let data = Data(text.utf8)

        // 過大なテキストはスキップ（設定可能、既定5MB）
        if data.count > settings.maxTextBytes { return }

        let hash = sha256Hex(data)
        let searchKey = Normalizer.normalize(text)
        let previewText = String(text.prefix(200))

        // コピー元アプリは検出時点の frontmostApplication（近似値。設計書 5.2）
        let frontApp = NSWorkspace.shared.frontmostApplication

        let newItem = HistoryStore.NewItem(
            createdAt: Int64(Date().timeIntervalSince1970 * 1000),
            kind: .text,
            previewText: previewText,
            searchKey: searchKey,
            contentHash: hash,
            sourceAppBundleID: frontApp?.bundleIdentifier,
            sourceAppName: frontApp?.localizedName,
            representations: [
                HistoryStore.NewRepresentation(uti: "public.utf8-plain-text", data: data)
            ]
        )

        do {
            let itemID = try historyStore.insert(newItem)
            onInsert?(IndexEntry(id: itemID, createdAt: newItem.createdAt, searchKey: searchKey))
        } catch {
            // DB書き込みに失敗しても監視ループ自体は継続する
            NSLog("ClipHistory: failed to insert history item: \(error)")
        }
    }
}
